spring.datasource.url=jdbc:postgresql://localhost:5432/publigana
spring.datasource.username=postgres
spring.datasource.password=b97041300306

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.jpa.show-sql=false