CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS rol (
    id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categoria_empresa (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS categoria (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activa BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS red_social (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    url_base VARCHAR(255),
    activa BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(20) UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL,
    ultimo_acceso TIMESTAMP,
    rol_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol(id_rol)
);

CREATE TABLE IF NOT EXISTS empresa (
    id_empresa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150),
    descripcion TEXT,
    direccion VARCHAR(255),
    telefono VARCHAR(20),
    correo VARCHAR(150),
    logo VARCHAR(255),
    sitio_web VARCHAR(255),
    estado BOOLEAN,
    fecha_registro TIMESTAMP,
    id_usuario UUID,
    id_categoria BIGINT,
    CONSTRAINT fk_empresa_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id),
    CONSTRAINT fk_empresa_categoria FOREIGN KEY (id_categoria) REFERENCES categoria_empresa(id_categoria)
);

CREATE TABLE IF NOT EXISTS campania (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titulo VARCHAR(150) NOT NULL,
    descripcion VARCHAR(4000) NOT NULL,
    bases VARCHAR(5000),
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    activa BOOLEAN NOT NULL,
    creador_id UUID NOT NULL,
    categoria_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campania_creador FOREIGN KEY (creador_id) REFERENCES usuario(id),
    CONSTRAINT fk_campania_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);

CREATE TABLE IF NOT EXISTS campania_red_social (
    campania_id UUID NOT NULL,
    red_social_id UUID NOT NULL,
    PRIMARY KEY (campania_id, red_social_id),
    CONSTRAINT fk_campania_red_social_campania FOREIGN KEY (campania_id) REFERENCES campania(id),
    CONSTRAINT fk_campania_red_social_red_social FOREIGN KEY (red_social_id) REFERENCES red_social(id)
);

CREATE TABLE IF NOT EXISTS publicacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contenido VARCHAR(5000) NOT NULL,
    enlace VARCHAR(500),
    fecha_programada TIMESTAMP,
    fecha_publicacion TIMESTAMP,
    estado VARCHAR(30) NOT NULL,
    empresa_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_publicacion_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id_empresa)
);

CREATE TABLE IF NOT EXISTS premio (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(1000),
    cantidad_disponible INT NOT NULL,
    valor_referencial NUMERIC(12,2),
    campania_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_premio_campania FOREIGN KEY (campania_id) REFERENCES campania(id)
);

CREATE TABLE IF NOT EXISTS participacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo_participacion VARCHAR(50) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL,
    fecha_participacion TIMESTAMP NOT NULL,
    usuario_id UUID NOT NULL,
    campania_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_participacion_campania FOREIGN KEY (campania_id) REFERENCES campania(id)
);

CREATE TABLE IF NOT EXISTS evidencia_participacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tipo VARCHAR(50) NOT NULL,
    url_archivo VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    participacion_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evidencia_participacion FOREIGN KEY (participacion_id) REFERENCES participacion(id)
);

CREATE TABLE IF NOT EXISTS sorteo (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campania_id UUID NOT NULL UNIQUE,
    fecha_sorteo TIMESTAMP NOT NULL,
    metodo VARCHAR(100) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sorteo_campania FOREIGN KEY (campania_id) REFERENCES campania(id)
);

CREATE TABLE IF NOT EXISTS ganador (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sorteo_id UUID NOT NULL,
    usuario_id UUID NOT NULL,
    premio_id UUID NOT NULL,
    fecha_seleccion TIMESTAMP NOT NULL,
    estado_notificacion VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ganador_sorteo FOREIGN KEY (sorteo_id) REFERENCES sorteo(id),
    CONSTRAINT fk_ganador_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_ganador_premio FOREIGN KEY (premio_id) REFERENCES premio(id)
);

CREATE TABLE IF NOT EXISTS notificacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id UUID NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    mensaje VARCHAR(2000) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    leida BOOLEAN NOT NULL,
    fecha_lectura TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS auditoria (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entidad_afectada VARCHAR(120) NOT NULL,
    entidad_id UUID NOT NULL,
    accion_realizada VARCHAR(50) NOT NULL,
    usuario_responsable_id UUID,
    fecha_accion TIMESTAMP NOT NULL,
    detalles_cambio VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_responsable_id) REFERENCES usuario(id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_id ON usuario(rol_id);
CREATE INDEX IF NOT EXISTS idx_empresa_usuario ON empresa(id_usuario);
CREATE INDEX IF NOT EXISTS idx_empresa_categoria ON empresa(id_categoria);
CREATE INDEX IF NOT EXISTS idx_campania_creador ON campania(creador_id);
CREATE INDEX IF NOT EXISTS idx_campania_categoria ON campania(categoria_id);
CREATE INDEX IF NOT EXISTS idx_publicacion_empresa ON publicacion(empresa_id);
CREATE INDEX IF NOT EXISTS idx_premio_campania ON premio(campania_id);
CREATE INDEX IF NOT EXISTS idx_participacion_usuario ON participacion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_participacion_campania ON participacion(campania_id);
CREATE INDEX IF NOT EXISTS idx_evidencia_participacion ON evidencia_participacion(participacion_id);
CREATE INDEX IF NOT EXISTS idx_ganador_sorteo ON ganador(sorteo_id);
CREATE INDEX IF NOT EXISTS idx_ganador_usuario ON ganador(usuario_id);
CREATE INDEX IF NOT EXISTS idx_ganador_premio ON ganador(premio_id);
CREATE INDEX IF NOT EXISTS idx_notificacion_usuario ON notificacion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON auditoria(usuario_responsable_id);

INSERT INTO rol (nombre, descripcion)
VALUES ('USER', 'Rol por defecto para usuarios registrados')
ON CONFLICT (nombre) DO NOTHING;
